require_relative 'coordinates'
require_relative 'directions'
require_relative 'move_checker'
require_relative 'fen_translator'
require_relative 'user_input'
require_relative 'square'
require_relative 'player'
require_relative 'move'
require_relative 'piece'
require_relative 'bishop'
require_relative 'no_piece'
require_relative 'board'
require_relative 'game'


